services:
  backend_nginx:
    build:
      context: ./backend-nginx
    container_name: wuth-backend-nginx

  backend_apache:
    build:
      context: ./backend-apache
    container_name: wuth-backend-apache

  nginx:
    image: nginx:1.27-alpine
    container_name: wuth-nginx
    depends_on:
      - backend_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  apache:
    image: httpd:2.4
    container_name: wuth-apache
    depends_on:
      - backend_apache
    ports:
      - "8083:80"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
